version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: golfclub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: golfclub
      MYSQL_DATABASE: golfclubdb
      MYSQL_USER: golfclub
      MYSQL_PASSWORD: golfclub
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - golfnet

  api:
    image: golfclub-api:latest
    build:
      context: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/golfclubdb
      SPRING_DATASOURCE_USERNAME: golfclub
      SPRING_DATASOURCE_PASSWORD: golfclub
    ports:
      - "8080:8080"
    networks:
      - golfnet

volumes:
  db_data:

networks:
  golfnet:

